apiVersion: v1
kind: Service
metadata:
  name: react-app-service
spec:
  selector:
    app: react-app
  ports:
    - protocol: TCP
      port: 81
      targetPort: 81
      nodePort: 30080  
  type: NodePort
